### ISSUE TITLE
How it work?

### ISSUE THREAD

**Issue by hhji** [rnplus/agar.io-private-server#1]
Execuse me, i have runned the private server by Qt5.4

then how to start the game in this server?

![default](https://cloud.githubusercontent.com/assets/11978090/7694614/5b4bd5e8-fe15-11e4-98a9-72c6fcc12520.png)

**Comment by WillRiches** [comment]
The server is now running. Open agar.io, connect to a server and press play, then type connect("ws://localhost:9000"); in the console.

**Comment by hhji** [comment]
Thanks.
So, type the  (ws://localhost:9000)  in the website agar.io ?

**Comment by WillRiches** [comment]
Yes, enter a game like normal, then during gameplay type:
    connect("ws://localhost:9000");
In the developer console of your web browser.
